In [1]:
import pandas as pd
import csv
import numpy as np

In [2]:
df = pd.read_csv('data_binary.csv')
df

    Length (cm)  Label (0->unripe 1->ripe)
0            15                          0
1            14                          0
2            16                          1
3            17                          1
4            13                          0
5            18                          1
6            16                          1
7            14                          0
8            15                          0
9            17                          1
10           13                          0
11           16                          1
12           14                          0
13           15                          0
14           17                          1
15           18                          1
16           13                          0
17           16                          1
18           14                          0
19           15                          0
20           17                          1
21           13                          0
22           16                          1
23           14                          0
24           15                          0
25           17                          1
26           18                          1
27           13                          0
28           16                          1
29           14                          0

In [3]:
data = {'Length (cm)': [], 'Label (0->unripe 1->ripe)': []}
with open('data_binary.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        data['Length (cm)'].append(float(row['Length (cm)']))
        data['Label (0->unripe 1->ripe)'].append(int(row['Label (0->unripe 1->ripe)']))

lengths = data['Length (cm)']
labels = data['Label (0->unripe 1->ripe)']

mean_length = sum(lengths) / len(lengths)
mean_label = sum(labels) / len(labels)

numerator = sum([(x - mean_length) * (y - mean_label) for x, y in zip(lengths, labels)])
denominator = sum([(x - mean_length) ** 2 for x in lengths])
slope = numerator / denominator

intercept = mean_label - slope * mean_length

print("Slope (m):", slope)34
print("Intercept (b):", intercept)

Slope (m): 0.2726081258191349
Intercept (b): -3.7042376583660976

In [4]:
def logistic_regression_predictor(x,slope,intercept):
    y = intercept+x*slope
    P = 1/(1+np.exp(1)**(-y))
    if P>0.5:
        print("The banana of length",x,"cm is ripe")
    else:
        print("The banana of length",x,"cm is not ripe")
    #print("The probabilty of a banana of length",x,"cm being ripe is",P,"hence, it is Ripe")

In [7]:
#input values
input = [19.8, 16.5, 15.7, 12.82, 14.23, 17, 14.9, 10.3]
for i in input:
    logistic_regression_predictor(i,slope,intercept)

The banana of length 19.8 cm is ripe
The banana of length 16.5 cm is ripe
The banana of length 15.7 cm is ripe
The banana of length 12.82 cm is not ripe
The banana of length 14.23 cm is ripe
The banana of length 17 cm is ripe
The banana of length 14.9 cm is ripe
The banana of length 10.3 cm is not ripe